name: Multi-Cloud CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Images
        run: |
          docker build -t frontend-app:1.0 ./frontend
          docker build -t backend-app:1.0 ./backend

      - name: Push Images to IBM Cloud Container Registry
        run: |
          ibmcloud login --apikey-3d2f0c90-3c91-4d7f-af60-691eb332fb41 -r us-south -g Default
          ibmcloud cr login
          docker tag frontend-app:1.0 us.icr.io/phase3projectibm/frontend-app:1.0
          docker tag backend-app:1.0 us.icr.io/phase3projectibm/backend-app:1.0
          docker push us.icr.io/phase3projectibm/frontend-app:1.0
          docker push us.icr.io/phase3projectibm/backend-app:1.0

      - name: Deploy to Kubernetes (IBM Cloud)
        run: |
          ibmcloud ks cluster config --cluster ${{ secrets.IBM_CLUSTER_NAME }}
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/backend-deployment.yaml